# Generated by Django 5.2.6 on 2025-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_ID', models.IntegerField()),
                ('Tables', models.CharField(max_length=50)),
                ('Guest_count', models.IntegerField()),
                ('Outwork_ID', models.IntegerField()),
                ('Sidework_ID', models.IntegerField()),
                ('Expected_in_time', models.TimeField()),
            ],
        ),
    ]
