# Generated by Django 5.2.6 on 2025-10-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_section_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='Outwork_ID',
        ),
        migrations.RemoveField(
            model_name='section',
            name='Sidework_ID',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.AlterField(
            model_name='section',
            name='Section_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Outwork',
            fields=[
                ('Outwork_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Outwork_label', models.CharField(max_length=100)),
                ('Outwork_difficulty', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outworks', to='servers.section')),
            ],
        ),
        migrations.CreateModel(
            name='Sidework',
            fields=[
                ('Sidework_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Sidework_label', models.CharField(max_length=100)),
                ('Sidework_difficulty', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideworks', to='servers.section')),
            ],
        ),
    ]
