# Generated by Django 5.2.6 on 2025-10-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_remove_section_outwork_id_remove_section_sidework_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('Host_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Host_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sa',
            fields=[
                ('sa_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('sa_name', models.CharField(max_length=100)),
            ],
        ),
    ]
